# Generated by Django 4.2.11 on 2024-05-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('is_active', 'pk'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
