# Generated by Django 4.2.11 on 2024-03-30 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата производства продукта'),
        ),
    ]
